# Generated by Django 6.0.1 on 2026-01-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('screen_type', models.CharField(max_length=30)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CpuManufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cpumanufacturer')),
                ('Manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer')),
                ('Network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.network')),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.os')),
            ],
        ),
    ]
