# Generated by Django 6.0.1 on 2026-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='cores',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='ram',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='storage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
