# Generated by Django 6.0.1 on 2026-01-22 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mobile_cores_mobile_ram_mobile_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
