# Generated by Django 6.0.1 on 2026-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mobile_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
