# Generated by Django 6.0.1 on 2026-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='mobile',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
